// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC909gcod6XTOIjAwZEmGmXYrei6cE7gyo',
    appId: '1:535320817233:web:60fac241229ca50b9ad270',
    messagingSenderId: '535320817233',
    projectId: 'quanlychitieu-2e7f1',
    authDomain: 'quanlychitieu-2e7f1.firebaseapp.com',
    storageBucket: 'quanlychitieu-2e7f1.firebasestorage.app',
    measurementId: 'G-4NBWXD5LJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fUHQ13QnGl17VoCllmF7J1X7AISrQVg',
    appId: '1:535320817233:android:396f37429bbc335a9ad270',
    messagingSenderId: '535320817233',
    projectId: 'quanlychitieu-2e7f1',
    storageBucket: 'quanlychitieu-2e7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kEF9QsId4dMyHzpELN1l1DpTfH6NmAU',
    appId: '1:535320817233:ios:3afde5a0f1068acf9ad270',
    messagingSenderId: '535320817233',
    projectId: 'quanlychitieu-2e7f1',
    storageBucket: 'quanlychitieu-2e7f1.firebasestorage.app',
    iosClientId: '535320817233-0q9cq0j9olb9jjpbtbqal874oqueh46i.apps.googleusercontent.com',
    iosBundleId: 'com.example.qlchitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7kEF9QsId4dMyHzpELN1l1DpTfH6NmAU',
    appId: '1:535320817233:ios:3afde5a0f1068acf9ad270',
    messagingSenderId: '535320817233',
    projectId: 'quanlychitieu-2e7f1',
    storageBucket: 'quanlychitieu-2e7f1.firebasestorage.app',
    iosClientId: '535320817233-0q9cq0j9olb9jjpbtbqal874oqueh46i.apps.googleusercontent.com',
    iosBundleId: 'com.example.qlchitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC909gcod6XTOIjAwZEmGmXYrei6cE7gyo',
    appId: '1:535320817233:web:af25d669fb72a4a69ad270',
    messagingSenderId: '535320817233',
    projectId: 'quanlychitieu-2e7f1',
    authDomain: 'quanlychitieu-2e7f1.firebaseapp.com',
    storageBucket: 'quanlychitieu-2e7f1.firebasestorage.app',
    measurementId: 'G-MYQR6WGFS9',
  );
}
